# Generated by Django 5.1.4 on 2025-02-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalcompleteprofile',
            name='price_traffic',
            field=models.PositiveIntegerField(default=0, help_text='Track the number of views or changes on pricing'),
        ),
        migrations.AlterField(
            model_name='professionalcompleteprofile',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('trimester', 'Trimester'), ('semester', 'Semester'), ('yearly', 'Yearly'), ('annually', 'Annually')], max_length=20, null=True),
        ),
    ]
