# Generated by Django 5.1.4 on 2025-02-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_professionalcompleteprofile_price_traffic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='session_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='domain',
            field=models.CharField(default='Web Development', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='mentor_name',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='plan_type',
            field=models.CharField(default='trimester', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='student_name',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='subdomains',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['mentor', 'student', 'status'], name='backend_boo_mentor__03adb7_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['transaction_id'], name='backend_boo_transac_a0ae15_idx'),
        ),
    ]
